### ISSUE TITLE
 Error: java.lang.ArrayIndexOutOfBoundsException: -1 

### ISSUE THREAD

**Issue by gonzaparra** [Albluca/rpgraph#2]
Dear Luca, 

I am using the Elastic Principal Tree package to calculate a tree using an initialization topology as follows:

computeElasticPrincipalGraph(Data = MatrixInput, NumNodes = 100, 
    NodesPositions = NodesInput, Edges = EdgesInput, 
    Method = "CurveConfiguration") 

I am able to get a result for some datasets but for others I get the error: " Error: java.lang.ArrayIndexOutOfBoundsException: -1 " and the details are pasted at the end. It is supposed to be using some index which exceeds the ones that are in the matrix, but I checked the structure for the inputs (Edges and Nodes inputs), but somehow I am not able to find the error.. 
I am able to get an output if I do not give an initial topology as an input so I guess the problem is there.. 

Any idea on what could be the reason? I attached the files used for the MatrixInput as well as the initial topology: NodesInput and EdgesInput. The calculations are made in 48 dimensions (columns in the input matrix).

Best

Gonzalo

------------

9 stop(structure(list(message = "java.lang.ArrayIndexOutOfBoundsException: -1", 
    call = NULL, jobj = <S4 object of class structure("jobjRef", package = "rJava")>), .Names = c("message", 
"call", "jobj"), class = c("ArrayIndexOutOfBoundsException", 
"IndexOutOfBoundsException", "RuntimeException", "Exception",  ... 
8 .jcheck(silent = FALSE) 
7 .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, 
    .jcast(if (inherits(o, "jobjRef") || inherits(o, "jarrayRef")) o else cl, 
        "java/lang/Object"), .jnew("java/lang/String", method), 
    j_p, j_pc, use.true.class = TRUE, evalString = simplify,  ... 
6 .jrcall(x, name, ...) 
5 cpg$graph$countNumberOfPointsProjected(.jcast(cpg$dataset, new.class = "/java/lang/String")) 
4 (function (Data, NumNodes, Parameters, NodesPositions = NULL, 
    Edges = NULL, ...) 
{
    StartTime <- Sys.time() ... 
3 do.call(computeElPT, append(list(Data = NewData, NumNodes = AllocatedNodes + 
    AddNodes, NodesPositions = NodesPositions, Edges = Edges, 
    Parameters = Parameters), ExtraArgs)) 
2 computeElasticPrincipalGraph(Data = ExpressionMatrix, NumNodes = N_yk, 
    NodesPositions = yk_profiles, Edges = ElasticTree[[1]]$Edges, 
    Method = "CurveConfiguration") 

[DataMatrix.txt](https://github.com/Albluca/rpgraph/files/711910/DataMatrix.txt)
[Edges.txt](https://github.com/Albluca/rpgraph/files/711909/Edges.txt)
[Nodes.txt](https://github.com/Albluca/rpgraph/files/711908/Nodes.txt)

**Comment by Albluca** [comment]
Hi Gonzalo,

thank your feedback. I was able to reproduce the error and fix the problem, but I need some time to fix the structure of the jar (there are a few duplicated files and I need to compare them ...), so I will update the package tomorrow morning :)

BW,
Luca

**Comment by Albluca** [comment]
I though I fixed the problem, but actually it is still not working properly. I'll let you know when it has been fixed.

**Comment by gonzaparra** [comment]
Thank you very much Luca :)

Best,

Gonzalo

-----
R. Gonzalo Parra, PhD
EMBO Postdoctoral Fellow
Quantitative and Computational Biology Group
http://www.mpibpc.mpg.de/de/soeding
Max Planck Institute for Biophysical Chemistry
Am Fassberg 11
37077, Göttingen, Germany

2017-01-18 12:17 GMT+01:00 Luca Albergante <notifications@github.com>:

**Comment by Albluca** [comment]
Hi Gonzalo,

I was finally able to find the root of the problem. Basically it is connected with the presence of very large values in the matrices of data points and is fully due to the java code. To give you an example with your data. After loading the data and libraries

library(rpgraph)
library(readr)

DataMatrix <- read_delim("~/Documents/R/DataMatrix.csv", ";", escape_double = FALSE, trim_ws = TRUE, col_names = FALSE,
                         col_types = "ddddddddddddddddddddddddddddddddddddddddddddddddddd")

Nodes <- read_delim("~/Documents/R/Nodes.txt", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
Edges <- read_delim("~/Documents/R/Edges.txt", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

if you use the data as there are, you will get an error

computeElasticPrincipalGraph(Data = data.matrix(DataMatrix),
                             NumNodes = 110,
                             NodesPositions = data.matrix(Nodes),
                             Edges = data.matrix(Edges),
                             Method = "CurveConfiguration")

but if you scale the matrix (for example by 100) it will work fine

computeElasticPrincipalGraph(Data = data.matrix(DataMatrix)/100,
                             NumNodes = 110,
                             NodesPositions = data.matrix(Nodes),
                             Edges = data.matrix(Edges),
                             Method = "CurveConfiguration")

I will look into the issue to find a proper solution, but it may take some time to be honest.

Best Wishes,
Luca

**Comment by gonzaparra** [comment]
Thank you very much for checking this, Luca!

I tried and I can calculate the trees by scaling the matrices.

I would appreciate if you could post here when you find a solution for the
package :)

Best,

Gonzalo

-----
R. Gonzalo Parra, PhD
EMBO Postdoctoral Fellow
Quantitative and Computational Biology Group
http://www.mpibpc.mpg.de/de/soeding
Max Planck Institute for Biophysical Chemistry
Am Fassberg 11
37077, Göttingen, Germany

2017-01-18 14:17 GMT+01:00 Luca Albergante <notifications@github.com>:

**Comment by Albluca** [comment]
Hi Gonzalo,

I was actually able to track down the java function responsible for the error and fix the code. I'm currently testing the new code and plan to update the package with the fixed java code by the end of the week.

BW,
Luca

**Comment by Albluca** [comment]
Hi Gonzalo,

I uploaded the updated jar file. This should fix the problem with data containing large values. Please let me know if you encounter any problem.

Note that there are now two jar files in the installation directory (colt.jar and VDAOEngine.jar). R should manage to install everything correctly if you do a fresh install. I also had to introduce a couple of 1-line changes in the R code, so coping the jar files will not be enough and you will have to update the package as well.

Best wishes,
Luca

**Comment by gonzaparra** [comment]
Hi Luca,

I tried the modified package and it works in the datasets that were raising
the error :)

Thanks for the fix!

Best,

Gonza

-----
R. Gonzalo Parra, PhD
EMBO Postdoctoral Fellow
Quantitative and Computational Biology Group
http://www.mpibpc.mpg.de/de/soeding
Max Planck Institute for Biophysical Chemistry
Am Fassberg 11
37077, Göttingen, Germany

2017-01-23 9:48 GMT+01:00 Luca Albergante <notifications@github.com>:
